#!/bin/dash

inn=0

if ! [ -d .shrug/"$1" ]
then
    echo "shrug-checkout: error: unknown branch 'non-existent-branch'"
    exit 0
fi

br=`cat .shrug/b_info.txt`
dl=""

# decide which file to remove from working file
for seg in `ls | egrep -v ^shrug- | egrep -v ^diary.txt$ | egrep -v ^.shrug$`
do
    if [ "$br" = "master" ]
    then
        id=`ls .shrug/"$br" | egrep ^[0-9]+$ | sort | tail -1`
        if [ "$id" != "" ]
        then
            if [ -f .shrug/master/$id/$seg ]
            then
                rt=`diff "$seg" .shrug/master/$id/$seg`
                if [ "$rt" != "" ]
                then
                    continue
                fi
            else
                continue
            fi
        else
            continue
        fi
    else
        bct=`ls .shrug/"$br" | wc -l`

        if [ "$bct" -ne 0 ] && [ -f .shrug/$br/$(($bct-1))/"$seg" ]
        then
            uy=`diff "$seg" .shrug/$br/$(($bct-1))/"$seg"`
            if [ "$uy" != "" ]
            then
                continue
            fi
        else
            if [ -f .shrug/index/"$seg" ]
            then
                echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:\n$seg"
                exit 0
            else
                continue
            fi
        fi
    fi
    dl=$dl" ""$seg"
done

# do remove operations
if [ "$dl" != "" ]
then
    for x in "$dl"
    do
        rm $x
    done
fi

# decide which files to copy from the new branch
id=`ls .shrug/master | egrep ^[0-9]+$ | sort | tail -1`
if [ "$1" = "master" ]
then
    if [ "$id" != "" ]
    then
        mct=`ls .shrug/master/"$id" | wc -l`
        if [ "$mct" -ne 0 ]
        then
            for f in `ls .shrug/master/"$id"`
            do
                if [ -f "$f" ]
                then
                    
                    if [ "$br" = "master" ]
                    then
                        tu=`diff "$f" .shrug/master/"$id"/"$f"`
                        if [ "$tu" != "" ]
                        then
                            continue
                        fi
                    else
                        bct=`ls .shrug/"$br" | wc -l`
                        if [ "$bct" -ne 0 ] && [ -f .shrug/"$br"/$(($bct-1))/"$f" ]
                        then
                            bw=`diff "$f" .shrug/"$br"/$(($bct-1))/"$f"`
                            if [ "$bw" != "" ]
                            then
                                continue
                            fi
                        else
                            continue
                        fi
                    fi
                fi 

                cp .shrug/master/"$id"/"$f" "$f"
            done
        fi
    fi
    echo master >.shrug/b_info.txt
    if [ "$inn" -eq 0 ]
    then
        echo "Switched to branch 'master'"
    fi
    exit 0
fi

bct=`ls .shrug/"$1" | wc -l`
bf=0
if [ "$bct" -ne 0 ]
then
    bf=`ls .shrug/"$1"/$(($bct-1)) | wc -l`
fi

nid=`ls .shrug/"$br" | egrep ^[0-9]+$ | sort | tail -1`

# decide which files to copy from the new branch
if [ "$bf" -ne 0 ]
then
    for file in `ls .shrug/"$1"/$(($bct-1))`
    do
        if ! [ -f "$file" ]
        then
            cp .shrug/"$1"/$(($bct-1))/"$file" "$file"
        elif [ "$nid" != "" ]
        then
            nct="$nid"
            while [ "$nct" != -1 ]
            do
                if ! [ -f .shrug/"$br"/"$nct"/"$file" ]
                then
                    nct=$(($nct-1))
                    continue
                fi
                buf=`diff "$file" .shrug/"$br"/"$nct"/"$file"`
            # tuf=`diff .shrug/"$1"/$(($bct-1))/"$file" .shrug/"$br"/"$nid"/"$file"`
            # if [ -f .shrug/index/"$file" ]
            # then
            #     icff=`diff .shrug/index/"$file" .shrug/"$br"/"$nid"/"$file"`
            # fi
                if [ "$buf" = "" ]
                then
                    cp .shrug/"$1"/$(($bct-1))/"$file" "$file"
                    break
                else
                    break
                fi
                nct=$(($nct-1))
            done
        fi
    done
fi

# change the branch infomation
echo "$1" >.shrug/b_info.txt
if [ "$inn" -eq 0 ]
then

    # idf=`ls .shrug/index | wc -l`
    # if [ "$idf" -ne 0 ]
    # then
    #     rm .shrug/index/*
    # fi

    # for wf in `ls | egrep -v ^shrug- | egrep -v ^diary.txt$ | egrep -v ^.shrug$`
    # do
    #     cp "$wf" .shrug/index/"$wf"
    # done

    echo "Switched to branch '$1'"
fi